#!/bin/sh

cat \
  bin/shell/disclaimer.sh    \
  bin/shell/detection.sh    \
  bin/shell/utility-functions.sh  \
  bin/shell/export.sh    \
  bin/shell/path.sh    \
  bin/shell/settings.sh    \
  bin/shell/pager.sh    \
  bin/shell/cmd-prompt.sh   \
  bin/shell/vim.sh    \
  bin/shell/subprocs-suck.sh    \
  bin/shell/dircolors.sh    \
  bin/shell/completion.sh    \
  bin/shell/gruvbox-colors.sh    \
  bin/shell/colors-basic.sh    \
  bin/shell/ansi-escapes.sh    \
  bin/shell/termcap-colors.sh    \
  bin/shell/tldr-colors.sh   \
  bin/shell/python.sh    \
  bin/shell/golang.sh    \
  bin/shell/alias.sh    \
  bin/shell/functions.sh    \
  bin/shell/personal.sh    \
>| bashrc
