#!/bin/bash

ln -sf $PWD/bashconfig $HOME/.bash_aliases
ls -l $HOME/.bash_aliases

ln -sf $PWD/dircolors $HOME/.dircolors
ls -l $HOME/.dircolors

mkdir -p $HOME/.ssh
ln -sf $PWD/sshconfig $HOME/.ssh/config
ls -l $HOME/.ssh/config

ln -sf $PWD/imwheelrc $HOME/.imwheelrc
ls -l $HOME/.imwheelrc

ln -sf $PWD/imwheel.desktop $HOME/.config/autostart/imwheel.desktop
ls -l $HOME/.config/autostart/imwheel.desktop

ln -sf $PWD/gitconfig $HOME/.gitconfig
ls -l $HOME/.gitconfig

ln -sf $PWD/inputrc $HOME/.inputrc
ls -l $HOME/.inputrc

sudo ln -sf $PWD/scripts/havecmd /usr/local/bin/havecmd
ls -l /usr/local/bin/havecmd

#curl -LJ -o ubuntu.ttf https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/UbuntuMono/Regular/complete/Ubuntu%20Mono%20Nerd%20Font%20Complete%20Mono.ttf
