#!/usr/bin/python3
import requests
## to-do: rewrite it in bash
## make it so you can pass ISBN as argument and then run it requests.get url at end needs variable
## also make it so it works together with pdf2isbn so you can extract an isbn. And create a file like `paper` does
r = requests.get("https://daas.library.ethz.ch/rib/v2/search?q=isbn,contains,9781408894620")
j = r.json()
s0 =j['docs'][0]['pnx']['search']
s1 =j['docs'][0]['pnx']['display']


print(f"creationdate: {s0['creationdate'][0]}")
## doesn't work with all books :( create if statements so those who have get this info
#print(f"keywords: {s0['subject']}")
print(f"ISBN: {s0['isbn'][0]}")
print(f"title: {s1['title'][0]}")
print(f"language: {s1['language'][0]}")
print(f"media type: {s1['type'][0]}")
print(f"publisher: {s1['publisher'][0]}")

#print(f"Book {s1['creationdate']}")
#print(f"{s0['general']}")
#print(f"{s0['title']}")
