#!/bin/sh

find .                          \
  -name '.git'                  \
  -prune -o                     \
  -exec grep -n -i --color=always "$1" {} \
  /dev/null                     \
  2>/dev/null \;
