#!/bin/sh

title="$1"

echo "<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>$title</title>
    <link rel="stylesheet" href="css/style.css">
  </head>
  <body>
    <header>
      <nav></nav>
      <h1>$title</h1>
      <h3>August 24&ndash;26th &mdash; Chicago, IL</h3>
    </header>
    <section class="hero container">
    </section>
    <footer>
      <small>&copy; 2020 Simon Donald Woodtli. All rights reserved.</small>
    </footer>
  </body>
</html>"
