#!/bin/bash
# ~/.newsboat/html2rss
target="https://robs.io/"
title=$(lynx -dump "https://robs.io/" | grep -E "^(Mo(n(day)?)?|Tu(e(s(day)?)?)?|We(d(nesday)?)?|Th(u(r(s(day)?)?)?)?|Fr(i(day)?)?|Sa(t(urday)?)?|Su(n(day)?)?)")

#^[a-z ,.'-]+[0-9]{2}, [0-9]{4}, [0-9]:[0-9]{2}:[0-9]{2}[A-Z]{2}
#Sunday, September 20, 2020, 12:39:29PM
#mapfile -t items < <(lynx -dump -listonly "$target" | sed "s|.*$target||" | grep xz)

cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">

  <channel>
    <title>$title</title>
    <link></link>
    <description>Stable review patches</description>

EOF
{
  for i in "$title"; do
    echo "    <item>"
    echo "      <title>$title</title>"
    echo "      <link></link>"
    echo "    </item>"
  done
  echo '  </channel>'
  echo '</rss>'
}
