#!/bin/bash
## adjust to your browser of choice: 
#export BROWSER='/usr/bin/brave-browser'
declare dependencies=( "fzf" "lynx" "git" "gh" "pandoc" )
declare missingDependencies=""

check_dependencies() {
  for dependency in ${dependencies[@]} ; do
    [[ $(type "$dependency" 2>/dev/null) ]] || missingDependencies+=" $dependency"
  done
  if [ "${#missingDependencies}" -gt 0 ] ; then
    echo "Missing dependencies:$missingDependencies."
    exit 1
  fi
}
check_dependencies

## no arguments given:
if [[ -z "$1" ]]; then
  ## if github repo open url in browser
  if [[ $(gh repo view 2>/dev/null) ]]; then
    gh repo view #show readme in terminal
    gh browse 2>/dev/null #open link in browser
    gh browse -n | tr -d "\n" | xclip -sel clipboard #copy url
  else
    ## if no git repo use fzf
    xdg-open "$(fd --type f | fzf)"
  fi
fi
## if url open browser
if [[ "$1" =~ ^http|^https:// ]]; then
  lynx "$1" && $BROWSER "$1" 2>/dev/null
fi
## if markdown file convert and open lynx
if [[ "$1" =~ \.md$ ]]; then
  pandoc -s -o /tmp/index.html "$1" 2>/dev/null
  lynx /tmp/index.html
  echo "markdown file detected"
fi
