#!/bin/sh

current_time=$(date "+%Y%m%d%H%M%S")
doi="$(pdf2doi ${1})"
bib=$(curl -s "http://api.crossref.org/works/$doi/transform/application/x-bibtex")
title=$(echo "$bib" | sed -n '1p' | cut -d{ -f2 | sed 's/,//')

cd $HOME/repos/github.com/SimonWoodtli/notes/papers
echo 'Do you want to add some tags?'
read tags
echo "\`\`\`yml
id: $current_time
tag: $tags
\`\`\`

~~~.bib
$bib
~~~

# Table of Contents

* [example](example-20200809150057.md)" >> index-$title-$current_time.md








