#!/bin/bash
## create a command that includes all these reddio commands

#rc() {
#  reddio print comments/$1 | less
#}
#
#rtm() {
#  reddio print -l 10 -t month r/$1/top | boxes -d dog | less
#}
#rtw() {
#  reddio print -l 10 -t week r/$1/top | boxes -d dog | less
#}
#
#rn() {
#  reddio print -l 10 r/$1 | boxes -d dog | less
#}
#
#alias ra='reddio | boxes -d dog | less'
