#!/bin/bash
## create a command that includes all these reddio commands
#declare subcommand="$1"; shift

# greet() {
# local name="$1"
# echo "Hello, $name"
# }
# greet "John Doe"
# greet $1

## Inside a function, $1 ... $n are the parameters passed to that function. Outside a function $1 ... $n are the parameters passed to the script.
## $1 works but $2 not why?

c() {
  local input="$2"
  reddio print comments/$input | less
  #echo yes
}

top() {
  local input="$2"
  echo $input
  reddio print -l 10 -t month r/$input/top #| boxes -d dog | less
}
top $2
echo $2
#top
#rtw() {
#  reddio print -l 10 -t week r/$1/top | boxes -d dog | less
#}
#
#rn() {
#  reddio print -l 10 r/$1 | boxes -d dog | less
#}
#
#alias ra='reddio | boxes -d dog | less'



## function call from $1 argument
declare -a commands=( c top)
for i in ${commands[@]}; do
  if [[ $i == "$subcommand" ]]; then
    "$subcommand" $*
    exit 0
  fi
done

## Tab completion - add to bashrc: `complete -C reddit reddit`
if [ -n "$COMP_LINE" ]; then
  for cmd in ${commands[@]}; do
    [[ "${cmd:0:${#1}}" == "$1" ]] && echo $cmd
  done
  exit 0
fi
