#!/bin/sh

current_time=$(date "+%Y%m%d%H%M%S")
echo "What's the files name?"
read who
echo 'Do you want to add some tags?'
read tags
touch "$who-$current_time.md"
echo "\`\`\`yml
id: $current_time
tag: $tags
\`\`\`" >> $who-$current_time.md

