#!/bin/sh

if [ -z "$(which vim)" -o -z "$(which vimtutor)" ]; then
  echo Need to install full vim.
  exit 1
fi

ln -sf "$PWD/vimrc" "$HOME/.vimrc"

mkdir -p $HOME/.vim/colors
ln -sf "$PWD/molokai.vim" "$HOME/.vim/colors/molokai.vim"
ln -sf "$PWD/hackerman.vim" "$HOME/.vim/colors/hackerman.vim"

